image: "mato/nethsm-builder@sha256:d21fdbce4449c9be8c74cd314b0b669d24737d2012bd276f0db54760d096dd2b"

default:
  before_script:
    - source .gitlab-ci-setup.bash
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - obj/artifacts/

stages:
  - build_dev
  - build_muen
  - test

build_keyfender:
  variables:
    MODE: dev
  stage: build_dev
  script:
    - make fetch-submodules
    - make -j$(nproc) build

test_keyfender:
  variables:
    MODE: test
  stage: test
  needs: []
  script:
    - make fetch-submodules
    - make -j$(nproc) coverage-summary

build_muen_qemu_kvm:
  variables:
    MODE: muen
    MUEN_HARDWARE: qemu-kvm
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make fetch-submodules
    - make -j$(nproc) build artifacts

build_muen_supermicro_x11ssh_tf:
  variables:
    MODE: muen
    MUEN_HARDWARE: supermicro-x11ssh-tf
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make fetch-submodules
    - make -j$(nproc) build artifacts
