image: "mato/nethsm-builder@sha256:d21fdbce4449c9be8c74cd314b0b669d24737d2012bd276f0db54760d096dd2b"

default:
  before_script:
    - source .gitlab-ci-setup.bash

stages:
  - build_dev
  - build_muen
  - test

build_keyfender:
  stage: build_dev
  script:
    - make -j$(nproc) build-keyfender

test_keyfender:
  stage: test
  needs: []
  script:
    - make -j$(nproc) MODE=test coverage-summary

build_muen_qemukvm:
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make -j$(nproc) MODE=muen MUEN_TARGET=qemu-kvm build

build_muen_x11sshtf:
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make -j$(nproc) MODE=muen MUEN_TARGET=supermicro-x11ssh-tf build
  artifacts:
    paths:
      - obj/coreboot.rom
      - obj/system.img.cpio
