image: "ocaml/opam:debian-10-ocaml-4.11-flambda"

stages:
  - build
  - test

build_keyfender:
  stage: build
  before_script:
    - ./.gitlab-ci-setup.bash
  script:
    - make build-keyfender

test_keyfender:
  stage: test
  before_script:
    - ./.gitlab-ci-setup.bash
    - sudo apt-get -y --no-install-recommends install parallel
  script:
    - make MODE=test coverage-summary
