image: "ocaml/opam2:debian-10-ocaml-4.10"

library_test:
  script:
    - cd ~/opam-repository && git pull && opam update && cd -
    - make test-keyfender-lib

make_keyfender:
  script:
    - cd ~/opam-repository && git pull && opam update && cd -
    - make build-keyfender
