image: "ocaml/opam:debian-10-ocaml-4.11-flambda"

stages:
  - build
  - test

build_keyfender:
  stage: build
  before_script:
    - cd ~/opam-repository && git fetch origin master && git reset --hard f86b6d27e1 && opam update && cd -
  script:
    - make build-keyfender

test_keyfender:
  stage: test
  before_script:
    - cd ~/opam-repository && git fetch origin master && git reset --hard f86b6d27e1 && opam update && cd -
    - sudo apt-get -y --no-install-recommends install parallel
  script:
    - make MODE=test coverage-summary
