image: "mato/nethsm-builder@sha256:d21fdbce4449c9be8c74cd314b0b669d24737d2012bd276f0db54760d096dd2b"

stages:
  - build
  - test

build_keyfender:
  stage: build
  before_script:
    - ./.gitlab-ci-setup.bash
  script:
    - make build-keyfender

test_keyfender:
  stage: test
  before_script:
    - ./.gitlab-ci-setup.bash
  script:
    - make MODE=test coverage-summary
