image: "ocaml/opam2:debian-10-ocaml-4.11"

stages:
  - build
  - test

build_keyfender:
  stage: build
  before_script:
    - cd ~/opam-repository && git pull && opam update && cd -
  script:
    - make build-keyfender

test_keyfender:
  stage: test
  before_script:
    - cd ~/opam-repository && git pull && opam update && cd -
    - sudo apt-get -y --no-install-recommends install parallel
  script:
    - make MODE=test coverage-summary
