image: "mato/nethsm-builder@sha256:d21fdbce4449c9be8c74cd314b0b669d24737d2012bd276f0db54760d096dd2b"

default:
  before_script:
    - source .gitlab-ci-setup.bash

stages:
  - build_dev
  - build_muen
  - test

build_keyfender:
  stage: build_dev
  script:
    - make fetch-submodules
    - make -j$(nproc) build-keyfender

test_keyfender:
  stage: test
  needs: []
  script:
    - make MODE=test fetch-submodules
    - make -j$(nproc) MODE=test coverage-summary

build_muen_qemu_kvm:
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make MODE=muen fetch-submodules
    - make -j$(nproc) MODE=muen MUEN_HARDWARE=qemu-kvm build artifacts
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - obj/artifacts/

build_muen_supermicro_x11ssh_tf:
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make MODE=muen fetch-submodules
    - make -j$(nproc) MODE=muen MUEN_HARDWARE=supermicro-x11ssh-tf build artifacts
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - obj/artifacts/
