variables:
  BUILDER_TAG: latest

.dependency_paths:
  builder: &builder_dep_paths
    - src/container/builder/**
    - .opam-repository-commit
    - .gitlab-ci.yml
  coreboot: &coreboot_dep_paths
    - src/coreboot/**
    - keys/**
    - .gitlab-ci.yml
    - Makefile*

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"
      when: never
    - changes:
        paths: *builder_dep_paths
      variables:
        BUILDER_TAG: ${CI_COMMIT_SHORT_SHA}
    - when: always

default:
  image: "${CI_REGISTRY_IMAGE}/builder:${BUILDER_TAG}"
  before_script:
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    - sudo chmod 01777 /downloads
    - mkdir -p /downloads/opam
    - rm -rf ~/.opam/download-cache
    - ln -s /downloads/opam ~/.opam/download-cache
  tags:
    - docker
  interruptible: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

stages:
  - prepare
  - build
  - build_muen
  - build_coreboot
  - deploy
  - check
  - build_docs
  - build_container

build_builder_image:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: ($BUILDER_TAG != "latest" && $CI_COMMIT_BRANCH != "master")
  stage: prepare
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - chmod 01777 /downloads
    - mkdir -p /kaniko/.docker
    - >
      echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf
      "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 |
      tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - if [ ${CI_PIPELINE_SOURCE} == "schedule" ] ; then NOPUSH="--no-push" ; fi
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/src/container/builder"
      --destination "${CI_REGISTRY_IMAGE}/builder:${CI_COMMIT_SHORT_SHA}"
      --cache=true
      --skip-unused-stages=true
      --build-arg GITLAB_TOKEN=${GITLAB_TOKEN}
      --build-arg OPAM_REPOSITORY_COMMIT=$(cat .opam-repository-commit)
      $NOPUSH

deploy_builder_image:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
  stage: deploy
  image:
    name: quay.io/skopeo/stable:latest
    entrypoint: [""]
  dependencies: []
  before_script:
    - echo $CI_REGISTRY_PASSWORD | skopeo login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - >
      if skopeo inspect docker://${CI_REGISTRY_IMAGE}/builder:${CI_COMMIT_SHORT_SHA} 2>/dev/null ;
      then skopeo copy docker://${CI_REGISTRY_IMAGE}/builder:${CI_COMMIT_SHORT_SHA}
      docker://${CI_REGISTRY_IMAGE}/builder:latest ; fi

build_dev:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH != "master"
  variables:
    MODE: dev
  stage: build
  needs:
    - job: build_builder_image
      optional: true
  script:
    - make -j$(nproc) build

test_keyfender:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" || $CI_PIPELINE_SOURCE == "schedule"
  variables:
    MODE: test
  stage: build
  needs:
    - job: build_builder_image
      optional: true
  script:
    - make -j$(nproc) coverage-summary

build_muen_qemu_kvm:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      variables:
        WITH_COREBOOT: "1"
    - if: $CI_COMMIT_BRANCH != "master"
      changes:
        paths: *coreboot_dep_paths
      variables:
        WITH_COREBOOT: "1"
    - if: $CI_COMMIT_BRANCH != "master"

  variables:
    MODE: muen
    MUEN_HARDWARE: qemu-kvm
  stage: build_muen
  needs:
    - job: build_builder_image
      optional: true
    - build_dev
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - obj/artifacts/
  script:
    - make -j$(nproc) build artifacts

build_muen_prodrive_hermes:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      variables:
        WITH_COREBOOT: "1"
    - if: $CI_COMMIT_BRANCH != "master"
      changes:
        paths: *coreboot_dep_paths
      variables:
        WITH_COREBOOT: "1"
    - if: $CI_COMMIT_BRANCH != "master"
  variables:
    MODE: muen
    MUEN_HARDWARE: prodrive-hermes-1.0
  stage: build_muen
  needs:
    - job: build_builder_image
      optional: true
    - build_dev
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - obj/artifacts/
  script:
    - make -j$(nproc) build artifacts

build_container_image:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH != "master"
  needs:
    - validate_api_spec
    - build_api_docs
  stage: build_container
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - chmod 01777 /downloads
    - mkdir -p /downloads/opam
    - mkdir -p /home/opam/.opam
    - ln -s /downloads/opam /home/opam/.opam/download-cache
    - mkdir -p /kaniko/.docker
    - >
      echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf
      "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 |
      tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - mv api_docs src/container/static/
    - mv api_spec/* src/container/static/api_docs/
    - cp docs/nethsm-api.raml src/container/static/api_docs/
    - if [ ${CI_PIPELINE_SOURCE} == "schedule" ] ; then NOPUSH="--no-push" ; fi
    - >-
      /kaniko/executor --context "${CI_PROJECT_DIR}"
      --dockerfile ${CI_PROJECT_DIR}/src/container/alpine/Dockerfile
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" $NOPUSH

deploy_container_image:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    IMAGE_NAME: "nitrokey/nethsm"
    IMAGE_TAG: "testing"
    REGISTRY: "docker.io"
  stage: deploy
  image:
    name: quay.io/skopeo/stable:latest
    entrypoint: [""]
  dependencies: []
  before_script:
    - echo $CI_REGISTRY_PASSWORD | skopeo login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - cat $DOCKERHUB_TOKEN | skopeo login -u $DOCKERHUB_USER --password-stdin $REGISTRY
  script:
    - skopeo copy docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA docker://$REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - skopeo copy docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA docker://$REGISTRY/$IMAGE_NAME:$IMAGE_TAG

validate_api_spec:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH != "master"
  variables:
    VALIDATOR: "node tools/api/convert_validate.js"
    API_SPEC: "docs/nethsm-api.raml"
  stage: check
  needs: []
  image: "node:alpine"
  dependencies: []
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - api_spec/
  before_script: []
  script:
    - npm install webapi-parser
    - $VALIDATOR < $API_SPEC
    - mkdir api_spec
    - cp gen_nethsm_api_* api_spec/

build_api_docs:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH != "master"
  variables:
    API_SPEC: "docs/nethsm-api.raml"
    NODE_OPTIONS: "--openssl-legacy-provider"
  stage: build_docs
  image: "node:alpine"
  dependencies: []
  needs:
    - validate_api_spec
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - api_docs/
  before_script: []
  script:
    - npm install api-console-cli
    - ./node_modules/.bin/api-console build -t "RAML 1.0" --app-title "NetHSM API"
      --verbose --strict -o api_docs/ $API_SPEC
