default:
  image: "mato/nethsm-builder@sha256:5315102997e3e163cb679317f332f3914adc2f30784360d8937edce1aae1e5d5"
  before_script:
    - source .gitlab-ci-setup.bash
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - obj/artifacts/
  interruptible: true

stages:
  - build_dev
  - build_muen
  - test
  - deploy

build_keyfender:
  except:
    variables:
      - ($CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule")
  variables:
    MODE: dev
  stage: build_dev
  script:
    - make fetch-submodules
    - make -j$(nproc) build

test_keyfender:
  except:
    variables:
      - ($CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule")
  variables:
    MODE: test
  stage: test
  needs: []
  script:
    - make fetch-submodules
    - make -j$(nproc) coverage-summary

build_muen_qemu_kvm:
  except:
    variables:
      - ($CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule")
  variables:
    MODE: muen
    MUEN_HARDWARE: qemu-kvm
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make fetch-submodules
    - make -j$(nproc) build artifacts

build_muen_supermicro_x11ssh_tf:
  except:
    variables:
      - ($CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule")
  variables:
    MODE: muen
    MUEN_HARDWARE: supermicro-x11ssh-tf
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make fetch-submodules
    - make -j$(nproc) build artifacts

build_muen_updater_supermicro_x11ssh_tf:
  except:
    variables:
      - ($CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule")
  variables:
    MODE: muen-updater
    MUEN_HARDWARE: supermicro-x11ssh-tf
  stage: build_muen
  needs: []
  script:
    - make fetch-submodules
    - make -j$(nproc) build artifacts

build_and_deploy_container_images:
  except:
    - schedules
  variables:
    DOCKER_HOST: tcp://docker:2375
    # This will instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
    IMAGE_NAME: "nitrokey/nethsm"
    IMAGE_TAG: "testing"
    REGISTRY: "docker.io"
  services:
    - docker:dind
  stage: deploy
  image: "docker"
  artifacts: {}
  before_script:
    - cat $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin $REGISTRY
  script:
    - cd src/container
    - >
      docker build --build-arg GIT_USER=gitlab-ci-token --build-arg
      GIT_PASSWORD=$CI_JOB_TOKEN --build-arg GIT_COMMIT=$CI_COMMIT_SHORT_SHA
      --tag $REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA -f alpine/Dockerfile .
    - |
      if [ $CI_COMMIT_BRANCH == "master" ] ; then
        docker tag $REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        docker push -a $REGISTRY/$IMAGE_NAME
      fi
