image: "mato/nethsm-builder@sha256:5315102997e3e163cb679317f332f3914adc2f30784360d8937edce1aae1e5d5"

default:
  before_script:
    - source .gitlab-ci-setup.bash
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - obj/artifacts/

stages:
  - build_dev
  - build_muen
  - test

build_keyfender:
  variables:
    MODE: dev
  stage: build_dev
  script:
    - make fetch-submodules
    - make -j$(nproc) build

test_keyfender:
  variables:
    MODE: test
  stage: test
  needs: []
  script:
    - make fetch-submodules
    - make -j$(nproc) coverage-summary

build_muen_qemu_kvm:
  variables:
    MODE: muen
    MUEN_HARDWARE: qemu-kvm
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make fetch-submodules
    - make -j$(nproc) build artifacts

build_muen_supermicro_x11ssh_tf:
  variables:
    MODE: muen
    MUEN_HARDWARE: supermicro-x11ssh-tf
  stage: build_muen
  needs: [build_keyfender]
  script:
    - make fetch-submodules
    - make -j$(nproc) build artifacts

build_muen_updater_supermicro_x11ssh_tf:
  variables:
    MODE: muen-updater
    MUEN_HARDWARE: supermicro-x11ssh-tf
  stage: build_muen
  needs: []
  script:
    - make fetch-submodules
    - make -j$(nproc) build artifacts
