image: "ocaml/opam2:debian-10-ocaml-4.10"

default:
  before_script:
    - cd ~/opam-repository && git pull && opam update && cd -

stages:
  - build
  - test

build_keyfender:
  stage: build
  script:
    - make build-keyfender

test_keyfender_lib:
  stage: test
  script:
    - make test-keyfender-lib

test_keyfender_api:
  stage: test
  script:
    - make test-keyfender-api

test_keyfender_e2e:
  stage: test
  script:
    - make test-keyfender-e2e
