name: nethsm-cluster

services:
  nethsm1:
    build:
      context: ../../..
      dockerfile: src/container/alpine/Dockerfile
      target: nethsm_test
      tags:
        - nethsm-dev
    networks:
      nethsm:
        interface_name: eth0
        ipv4_address: 172.22.1.2
      int1:
        interface_name: eth1
        link_local_ips:
          - 169.254.169.1
    # environment: {}
    cap_add:
      - NET_ADMIN
    depends_on:
      - etcd1
  etcd1:
    image: "quay.io/coreos/etcd:v3.6.5"
    networks:
      int1:
        link_local_ips:
          - 169.254.169.2
    command: >
      etcd
        --listen-client-urls "http://169.254.169.2:2379"
        --advertise-client-urls "http://169.254.169.2:2379"
        --data-dir /etcd-data/etcd1
        --host-whitelist "169.254.169.1"
        --max-txn-ops 512
    # --log-level debug
    volumes:
      - data:/etcd-data

  nethsm2:
    image: nethsm-dev
    networks:
      nethsm:
        interface_name: eth0
        ipv4_address: 172.22.1.3
      int2:
        interface_name: eth1
        link_local_ips:
          - 169.254.169.1
    # environment: {}
    cap_add:
      - NET_ADMIN
    depends_on:
      - nethsm1
      - etcd2
  etcd2:
    image: "quay.io/coreos/etcd:v3.6.5"
    networks:
      int2:
        link_local_ips:
          - 169.254.169.2
    command: >
      etcd
        --listen-client-urls "http://169.254.169.2:2379"
        --advertise-client-urls "http://169.254.169.2:2379"
        --data-dir /etcd-data/etcd2
        --host-whitelist "169.254.169.1"
        --max-txn-ops 512
    # --log-level debug
    volumes:
      - data:/etcd-data

  nethsm3:
    image: nethsm-dev
    networks:
      nethsm:
        interface_name: eth0
        ipv4_address: 172.22.1.4
      int3:
        interface_name: eth1
        link_local_ips:
          - 169.254.169.1
    # environment: {}
    cap_add:
      - NET_ADMIN
    depends_on:
      - nethsm1
      - etcd3
  etcd3:
    image: "quay.io/coreos/etcd:v3.6.5"
    networks:
      int3:
        link_local_ips:
          - 169.254.169.2
    command: >
      etcd
        --listen-client-urls "http://169.254.169.2:2379"
        --advertise-client-urls "http://169.254.169.2:2379"
        --data-dir /etcd-data/etcd3
        --host-whitelist "169.254.169.1"
        --max-txn-ops 512
    # --log-level debug
    volumes:
      - data:/etcd-data

  # nethsm4:
  #   build:
  #     context: ../../..
  #     dockerfile: src/container/alpine/Dockerfile
  #     target: nethsm_test
  #   networks:
  #     nethsm:
  #       interface_name: eth0
  #       ipv4_address: 172.22.1.5
  #     int4:
  #       interface_name: eth1
  #       link_local_ips:
  #         - 169.254.169.1
  #   # environment: {}
  #   cap_add:
  #     - NET_ADMIN
  #   depends_on:
  #     - etcd4
  # etcd4:
  #   image: "quay.io/coreos/etcd:v3.6.5"
  #   networks:
  #     int4:
  #       link_local_ips:
  #         - 169.254.169.2
  #   command: >
  #     etcd
  #       --listen-client-urls "http://169.254.169.2:2379"
  #       --advertise-client-urls "http://169.254.169.2:2379"
  #       --data-dir /etcd-data/etcd3
  #       --host-whitelist "169.254.169.1"
  #       --max-txn-ops 512
  #   # --log-level debug
  #   volumes:
  #     - data:/etcd-data

  # etcd-witness:
  #   image: "quay.io/coreos/etcd:v3.6.5"
  #   networks:
  #     nethsm:
  #       ipv4_address: 172.22.1.10
  #   command: >
  #     etcd
  #       --data-dir=/etcd-data/etcd-witness
  #       --cert-file=/run/secrets/etcd_server_cert
  #       --key-file=/run/secrets/etcd_server_key
  #       --trusted-ca-file=/run/secrets/ca_cert
  #       --advertise-client-urls=https://0.0.0.0:2379
  #       --listen-client-urls=https://0.0.0.0:2379
  #       --max-txn-ops=512
  #   volumes:
  #     - data:/etcd-data
  #   secrets:
  #     - ca_cert
  #     - etcd_server_cert
  #     - etcd_server_key

  nethsm-test:
    image: nethsm-dev
    depends_on:
      - nethsm1
      - nethsm2
      - nethsm3
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |-
        curl -f -k -s -w '\n' https://nethsm1/api/v1/info
        curl -f -k -s -w '\n' https://nethsm2/api/v1/info
        curl -f -k -s -w '\n' https://nethsm3/api/v1/info
        sleep 1000
    networks:
      - nethsm

networks:
  nethsm:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "172.22.1.0/24"
  int1:
    internal: true
  int2:
    internal: true
  int3:
    internal: true
  int4:
    internal: true
volumes:
  data:
# secrets:
#   ca_cert:
#     file: ./certs/ca.crt
#   etcd_client_cert:
#     file: ./certs/client.crt
#   etcd_client_key:
#     file: ./certs/client.key
#   etcd_server_cert:
#     file: ./certs/server.crt
#   etcd_server_key:
#     file: ./certs/server.key
#   device_key:
#     file: ./device_key.txt

